apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: bookstore
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
      tier: database
  template:
    metadata:
      labels:
        app: bookstore
        tier: database
    spec:
      securityContext:
        runAsUser: 1001 # عشان متشتغلش بـ root زي ما هو طالب
      containers:
      - name: mysql
        image: docker.io/ahmedhusseinabdelkader/bookstore-db:v1 # صورتك اللي رفعناها
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "bookstore123" # يفضل لاحقاً نستخدم Secret
        - name: MYSQL_DATABASE
          value: "bookstore"
        - name: MYSQL_USER
          value: "bookstore"
        - name: MYSQL_PASSWORD
          value: "bookstore123"
        resources: # ضرورية عشان نقاط الـ Resource Limits
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe: # ضرورية لنقاط الـ Health Checks
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost"]
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mysql # ده الاسم اللي الباك اند هيكلم بيه الداتا بيز
spec:
  ports:
  - port: 3306
  selector:
    app: bookstore
    tier: database
