name: CI/CD Bookstore Pipeline

on:
  push:
    branches: [ main ] # هيشتغل أول ما تعمل push على فرع main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-backend:v1 ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-backend:v1

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-frontend:v1 ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-frontend:v1

      # خطوة الـ Deploy لـ OpenShift (بتحتاج Token من الأوبن شيفت)
      - name: Install OC CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
          tar -xvzf openshift-client-linux.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Deploy to OpenShift
        run: |
          oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}
          oc apply -k openshift/base/
          oc rollout restart deployment/frontend deployment/backend
